export const NAME_SITE = "Rueda Leather Wallets"
export const NAME_SITE_MIN = "RLW"
export const AUTHOR_NAME_SITE = "ivanruedas85"
export const AUTHOR_MAIL = "ruedaleatherwhallets@gmail.com"
export const AUTHOR_NUMBER_PHONE = "+529371035628"