export const NAME_SITE = "Rueda Leather Wallets"
export const NAME_SITE_MIN = "RLW"
export const AUTHOR_NAME_SITE = "ivanruedas85"
export const AUTHOR_MAIL = "darthmaul666@protonmail.com"
export const AUTHOR_NUMBER_PHONE = "+529371389398"